name: Enhanced WakaTime Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs at 12 AM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: WakaTime Stats Update
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_LANGUAGES: True
          SHOW_EDITORS: True
          SHOW_TIMEZONE: 'UTC-0'

      - name: Generate Stats Graphics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ''
          plugin_wakatime: 'yes'
          plugin_wakatime_sections: 'time, projects, languages, editors'
          plugin_wakatime_duration: 'last_7_days'

      - name: Update README
        run: |
          sed -i '/<!--START_SECTION:waka-->/, /<!--END_SECTION:waka-->/c\<!--START_SECTION:waka-->\n\!\[\]\(metrics.plugin.wakatime.svg\)\n<!--END_SECTION:waka-->' README.md
        shell: bash

        
      - name: List files in the directory
        run: ls -la

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update WakaTime statistics"
          file_pattern: README.md metrics.plugin.wakatime.svg
